apiVersion: v1
kind: Pod
metadata:
  name: retail-pod
  namespace: mahesh-ns
  labels:
    app: retail-cart
spec:
  containers:
    - name: retail-container
      image: maheshnandi/flower-backend:latest
      ports:
        - containerPort: 3000